var defined = typeof defined === "undefined" ? {} : defined;
defined.dpd_roots = {
  '√acc 1': {en: 'shine, praise', es: 'brillar, alabar'},
  '√acc 2': {en: 'worship', es: 'adorar'},
  '√ad': {en: 'eat', es: 'comer'},
  '√add': {en: 'afflict', es: 'afligir'},
  '√agg': {en: 'move crookedly', es: 'moverse torcidamente'},
  '√aggh': {en: 'be worth', es: 'valer'},
  '√ah': {en: 'speak', es: 'hablar'},
  '√aj': {en: 'go, drive', es: 'ir, conducir'},
  '√akkh': {en: 'see', es: 'ver'},
  '√an': {en: 'breathe, blow', es: 'respirar, soplar'},
  '√ap': {en: 'reach, attain', es: 'alcanzar, lograr'},
  '√ar': {en: 'move, attain', es: 'moverse, alcanzar'},
  '√arah': {en: 'deserve, be worthy', es: 'merecer, ser digno'},
  '√as 1': {en: 'be', es: 'ser'},
  '√as 2': {en: 'throw, hurl', es: 'lanzar, arrojar'},
  '√as 3': {en: 'eat', es: 'comer'},
  '√as 4': {en: 'eat', es: 'comer'},
  '√atth': {en: 'wish for', es: 'desear'},
  '√añc': {en: 'bend', es: 'doblar'},
  '√añch': {en: 'extend, draw along', es: 'extender, arrastrar'},
  '√añj 1': {en: 'distinguish', es: 'distinguir'},
  '√añj 2': {en: 'smear, anoint', es: 'untar, ungir'},
  '√añj 3': {en: 'pay respect', es: 'rendir respeto'},
  '√aḍḍ': {en: 'judge', es: 'juzgar'},
  '√aṃs': {en: 'divide, distribute', es: 'dividir, distribuir'},
  '√aṅg': {en: 'walk', es: 'caminar'},
  '√aṇ': {en: 'recite', es: 'recitar'},
  '√aṭ': {en: 'roam, wander', es: 'vagar, deambular'},
  '√badh': {en: 'bind, tie', es: 'atar, amarrar'},
  '√bah 1': {en: 'be outside', es: 'estar afuera'},
  '√bah 2': {en: 'increase', es: 'aumentar'},
  '√bal': {en: 'be strong, live', es: 'ser fuerte, vivir'},
  '√bandh': {en: 'bind, tie', es: 'atar, amarrar'},
  '√bhad': {en: 'be good, be lucky', es: 'ser bueno, ser afortunado'},
  '√bhaj 1': {en: 'divide, distribute', es: 'dividir, distribuir'},
  '√bhaj 2': {en: 'associate, keep company', es: 'asociarse, acompañar'},
  '√bhajj': {en: 'cook', es: 'cocinar'},
  '√bhakkh': {en: 'eat', es: 'comer'},
  '√bham': {en: 'turn, revolve, buzz', es: 'girar, rotar, zumbar'},
  '√bhar': {en: 'carry, support', es: 'llevar, sostener'},
  '√bhas 1': {en: 'fall down', es: 'caer'},
  '√bhañj': {en: 'break, destroy', es: 'romper, destruir'},
  '√bhaṇ': {en: 'talk, speak', es: 'hablar, decir'},
  '√bhaṇḍ': {en: 'blame, accuse', es: 'culpar, acusar'},
  '√bhid': {en: 'break, split', es: 'romper, partir'},
  '√bhikkh': {en: 'beg', es: 'mendigar'},
  '√bhis': {en: 'fear', es: 'temer'},
  '√bhuj 1': {en: 'use, eat, enjoy', es: 'usar, comer, disfrutar'},
  '√bhuj 2': {en: 'bend', es: 'doblar'},
  '√bhus': {en: 'fall heavily', es: 'caer pesadamente'},
  '√bhuss': {en: 'bark', es: 'ladrar'},
  '√bhā': {en: 'shine, speak', es: 'brillar, hablar'},
  '√bhās 1': {en: 'speak', es: 'hablar'},
  '√bhās 2': {en: 'shine', es: 'brillar'},
  '√bhī': {en: 'fear', es: 'temer'},
  '√bhū': {en: 'be, become', es: 'ser, llegar a ser'},
  '√bhūs': {en: 'adorn, decorate', es: 'adornar, decorar'},
  '√bil': {en: 'break, chop', es: 'romper, cortar'},
  '√brah': {en: 'increase', es: 'aumentar'},
  '√brū': {en: 'say', es: 'decir'},
  '√brūh': {en: 'increase', es: 'aumentar'},
  '√budh': {en: 'know, wake up', es: 'conocer, despertar'},
  '√buh': {en: 'pluck out, uproot', es: 'arrancar, desarraigar'},
  '√bādh': {en: 'press, oppress', es: 'presionar, oprimir'},
  '√cabb': {en: 'chew, spit out', es: 'masticar, escupir'},
  '√caj': {en: 'give up, let go', es: 'renunciar, soltar'},
  '√cakkh': {en: 'see', es: 'ver'},
  '√cal': {en: 'shake, tremble', es: 'sacudir, temblar'},
  '√cam': {en: 'wash, rinse', es: 'lavar, enjuagar'},
  '√cand': {en: 'glow, be bright', es: 'resplandecer, ser brillante'},
  '√car 1': {en: 'move, walk', es: 'moverse, caminar'},
  '√car 2': {en: 'act, behave', es: 'actuar, comportarse'},
  '√caṇḍ': {en: 'be fierce, be violent', es: 'ser feroz, ser violento'},
  '√chad': {en: 'cover, conceal', es: 'cubrir, ocultar'},
  '√chand': {en: 'desire, please', es: 'desear, agradar'},
  '√chaḍḍ': {en: 'discard, abandon', es: 'descartar, abandonar'},
  '√chid': {en: 'cut, divide', es: 'cortar, dividir'},
  '√chubh': {en: 'throw out', es: 'arrojar'},
  '√chup': {en: 'touch', es: 'tocar'},
  '√chuṭ': {en: 'cut off', es: 'cortar'},
  '√chā': {en: 'be hungry', es: 'tener hambre'},
  '√ci 1': {en: 'gather, accumulate', es: 'reunir, acumular'},
  '√ci 2': {en: 'note, observe', es: 'notar, observar'},
  '√cikkh': {en: 'show, tell', es: 'mostrar, decir'},
  '√cil': {en: 'clothe', es: 'vestir'},
  '√cint': {en: 'think', es: 'pensar'},
  '√cit 1': {en: 'think, intend', es: 'pensar, intentar'},
  '√cit 2': {en: 'mark', es: 'marcar'},
  '√citt': {en: 'paint, design', es: 'pintar, diseñar'},
  '√ciṭ': {en: 'send, abuse', es: 'enviar, insultar'},
  '√cu': {en: 'shift, fall away, die', es: 'desplazarse, decaer, morir'},
  '√cud': {en: 'impel, accuse', es: 'impulsar, acusar'},
  '√cumb': {en: 'kiss', es: 'besar'},
  '√cup': {en: 'move', es: 'moverse'},
  '√cur': {en: 'steal', es: 'robar'},
  '√cuṇṇ': {en: 'grind, crush, powder', es: 'moler, triturar, pulverizar'},
  '√cāy': {en: 'honour', es: 'honrar'},
  '√dah': {en: 'be strong', es: 'ser fuerte'},
  '√dakkh': {en: 'be able, please', es: 'ser capaz, agradar'},
  '√dal': {en: 'split, tear apart', es: 'partir, desgarrar'},
  '√dam': {en: 'be tame', es: 'ser manso'},
  '√dandh': {en: 'be slow', es: 'ser lento'},
  '√dap': {en: 'be arrogant', es: 'ser arrogante'},
  '√dar 1': {en: 'break, split apart', es: 'romper, partir'},
  '√dar 2': {en: 'fear', es: 'temer'},
  '√dar 3': {en: 'respect, have affection', es: 'respetar, tener afecto'},
  '√day': {en: 'be kind, have pity', es: 'ser amable, tener piedad'},
  '√dev': {en: 'lament', es: 'lamentar'},
  '√dhaj': {en: 'move, flap', es: 'moverse, ondear'},
  '√dham': {en: 'blow, sound', es: 'soplar, sonar'},
  '√dhan 1': {en: 'be rich', es: 'ser rico'},
  '√dhan 2': {en: 'sound', es: 'sonar'},
  '√dhar 1': {en: 'hold, carry, endure', es: 'sostener, llevar, soportar'},
  '√dhar 2': {en: 'wear, hold, carry', es: 'vestir, sostener, llevar'},
  '√dhaṃs': {en: 'fall down, destroy', es: 'caer, destruir'},
  '√dhe': {en: 'drink, suck', es: 'beber, succionar'},
  '√dhov': {en: 'wash, sharpen', es: 'lavar, afilar'},
  '√dhur': {en: 'be crooked, be corrupt', es: 'ser torcido, ser corrupto'},
  '√dhuv': {en: 'be firm, be solid', es: 'ser firme, ser sólido'},
  '√dhā': {en: 'place, support', es: 'colocar, sostener'},
  '√dhāv 1': {en: 'run, flow', es: 'correr, fluir'},
  '√dhāv 2': {en: 'polish, sharpen', es: 'pulir, afilar'},
  '√dhī': {en: 'think', es: 'pensar'},
  '√dhū': {en: 'shake, smoke', es: 'sacudir, humear'},
  '√dhūp': {en: 'smoke', es: 'humear'},
  '√dih': {en: 'accumulate, smear', es: 'acumular, untar'},
  '√dikkh': {en: 'consecrate', es: 'consagrar'},
  '√dis 1': {en: 'see', es: 'ver'},
  '√dis 2': {en: 'point out, explain', es: 'señalar, explicar'},
  '√dis 3': {en: 'dislike, hate', es: 'desagradar, odiar'},
  '√div': {en: 'shine', es: 'brillar'},
  '√dru': {en: 'run, flow', es: 'correr, fluir'},
  '√du': {en: 'burn, torment', es: 'quemar, atormentar'},
  '√dubbh': {en: 'deceive, be treacherous', es: 'engañar, ser traicionero'},
  '√duh': {en: 'milk a cow', es: 'ordeñar'},
  '√dukkh': {en: 'be painful', es: 'ser doloroso'},
  '√dul': {en: 'swing', es: 'balancear'},
  '√dus 1': {en: 'be angry, be corrupt', es: 'estar enojado, ser corrupto'},
  '√dus 2': {en: 'hate, dislike', es: 'odiar, desagradar'},
  '√dvar': {en: 'obstruct, prohibit', es: 'obstruir, prohibir'},
  '√dā 1': {en: 'give', es: 'dar'},
  '√dā 2': {en: 'be pure, be clean', es: 'ser puro, ser limpio'},
  '√dā 3': {en: 'tie, bind', es: 'atar, amarrar'},
  '√dā 4': {en: 'cut, break apart', es: 'cortar, romper'},
  '√dā 5': {en: 'sleep', es: 'dormir'},
  '√dī': {en: 'be afflicted', es: 'estar afligido'},
  '√dīp': {en: 'shine, explain', es: 'brillar, explicar'},
  '√dū': {en: 'go, run', es: 'ir, correr'},
  '√edh': {en: 'flourish, prosper', es: 'florecer, prosperar'},
  '√ej': {en: 'move, shake', es: 'moverse, sacudir'},
  '√es': {en: 'seek, search', es: 'buscar, indagar'},
  '√gabbh': {en: 'be bold, be daring', es: 'ser audaz, ser osado'},
  '√gad': {en: 'speak', es: 'hablar'},
  '√gadh': {en: 'bind, tie', es: 'atar, amarrar'},
  '√gah': {en: 'grasp', es: 'agarrar'},
  '√gaj': {en: 'roar, make sound', es: 'rugir, hacer sonido'},
  '√gajj': {en: 'roar, thunder', es: 'rugir, tronar'},
  '√gal 1': {en: 'drip, flow', es: 'gotear, fluir'},
  '√gal 2': {en: 'eat', es: 'comer'},
  '√gam': {en: 'go', es: 'ir'},
  '√gandh': {en: 'hurt, harm', es: 'herir, dañar'},
  '√ganth': {en: 'tie, bind', es: 'atar, amarrar'},
  '√gar 1': {en: 'esteem, be heavy', es: 'estimar, ser pesado'},
  '√gar 2': {en: 'drip, swallow', es: 'gotear, tragar'},
  '√garah': {en: 'blame', es: 'culpar'},
  '√gas': {en: 'eat, swallow', es: 'comer, tragar'},
  '√gaves': {en: 'seek, search', es: 'buscar, indagar'},
  '√gaṇ': {en: 'calculate, group', es: 'calcular, agrupar'},
  '√ghar 1': {en: 'drip', es: 'gotear'},
  '√ghar 2': {en: 'burn, be hot', es: 'quemar, estar caliente'},
  '√ghas': {en: 'eat', es: 'comer'},
  '√ghaṃs': {en: 'rub, grind, pound', es: 'frotar, moler, machacar'},
  '√ghaṭ 1': {en: 'strike, kill', es: 'golpear, matar'},
  '√ghaṭ 2': {en: 'join together', es: 'unir'},
  '√ghaṭ 3': {en: 'be busy with, strive', es: 'ocuparse de, esforzarse'},
  '√ghaṭṭ 1': {en: 'hit, strike', es: 'golpear, pegar'},
  '√ghaṭṭ 2': {en: 'join together', es: 'unir'},
  '√ghur': {en: 'scream, be awful', es: 'gritar, ser terrible'},
  '√ghus': {en: 'shout, make noise', es: 'gritar, hacer ruido'},
  '√ghā': {en: 'smell', es: 'oler'},
  '√gidh': {en: 'be greedy', es: 'ser codicioso'},
  '√gil': {en: 'eat, swallow', es: 'comer, tragar'},
  '√gilā': {en: 'be sick, be tired', es: 'estar enfermo, estar cansado'},
  '√gir 1': {en: 'raise', es: 'elevar'},
  '√gir 2': {en: 'call, speak', es: 'llamar, hablar'},
  '√guh': {en: 'hide, conceal', es: 'esconder, ocultar'},
  '√gumph': {en: 'tie, string together', es: 'atar, ensartar'},
  '√gup 1': {en: 'dislike', es: 'desagradar'},
  '√gup 2': {en: 'guard', es: 'guardar'},
  '√guḷ': {en: 'roll around, protect', es: 'rodar, proteger'},
  '√guṇ': {en: 'repeat, multiply', es: 'repetir, multiplicar'},
  '√guṇṭh': {en: 'enclose, envelope', es: 'encerrar, envolver'},
  '√gā': {en: 'sing', es: 'cantar'},
  '√gādh': {en: 'stand firmly', es: 'estar firme'},
  '√gāh': {en: 'dive, plunge', es: 'sumergirse, zambullirse'},
  '√gū': {en: 'excrete', es: 'excretar'},
  '√had': {en: 'excrete', es: 'excretar'},
  '√han': {en: 'strike, kill', es: 'golpear, matar'},
  '√har 1': {en: 'carry', es: 'llevar'},
  '√har 2': {en: 'take, seize', es: 'tomar, agarrar'},
  '√har 3': {en: 'live', es: 'vivir'},
  '√har 4': {en: 'be ashamed', es: 'avergonzarse'},
  '√hariy': {en: 'like', es: 'gustar'},
  '√has': {en: 'elate, laugh', es: 'regocijar, reír'},
  '√haṃs': {en: 'rise, elate', es: 'elevarse, regocijar'},
  '√haṭ': {en: 'shine', es: 'brillar'},
  '√heṭh': {en: 'harass, annoy', es: 'acosar, molestar'},
  '√hi 1': {en: 'send', es: 'enviar'},
  '√hi 2': {en: 'impel', es: 'impulsar'},
  '√hikk': {en: 'hiccup', es: 'hipar'},
  '√hir': {en: 'be ashamed', es: 'avergonzarse'},
  '√his': {en: 'hurt, harm', es: 'herir, dañar'},
  '√hiṇḍ': {en: 'roam, wander', es: 'vagar, deambular'},
  '√hu': {en: 'pour, offer as oblation', es: 'verter, ofrecer como oblación'},
  '√hā 1': {en: 'abandon', es: 'abandonar'},
  '√hā 2': {en: 'decrease', es: 'disminuir'},
  '√hīḷ': {en: 'scorn', es: 'despreciar'},
  '√hū': {en: 'be', es: 'ser'},
  '√i 1': {en: 'come, go', es: 'venir, ir'},
  '√i 2': {en: 'study, recite', es: 'estudiar, recitar'},
  '√idh': {en: 'succeed, accomplish', es: 'lograr, realizar'},
  '√ikkh': {en: 'see, mark', es: 'ver, marcar'},
  '√indh': {en: 'fire, burn', es: 'encender, quemar'},
  '√is': {en: 'wish for', es: 'desear'},
  '√iss': {en: 'be envious, be jealous', es: 'ser envidioso, ser celoso'},
  '√iñj': {en: 'move, shake', es: 'moverse, sacudir'},
  '√jagg': {en: 'look after', es: 'cuidar'},
  '√jaggh': {en: 'laugh', es: 'reír'},
  '√jakkh': {en: 'eat', es: 'comer'},
  '√jal 1': {en: 'shine, blaze', es: 'brillar, arder'},
  '√jal 2': {en: 'hide, conceal', es: 'esconder, ocultar'},
  '√jambh': {en: 'yawn, stretch, wake up', es: 'bostezar, estirarse, despertar'},
  '√jan': {en: 'be born, produce', es: 'nacer, producir'},
  '√japp': {en: 'mutter, pray', es: 'murmurar, rezar'},
  '√jar': {en: 'age', es: 'envejecer'},
  '√jaṭ': {en: 'twist, tangle', es: 'torcer, enredar'},
  '√jhap': {en: 'burn, blaze', es: 'quemar, arder'},
  '√jhe': {en: 'burn, blaze', es: 'quemar, arder'},
  '√jhā': {en: 'think, meditate', es: 'pensar, meditar'},
  '√ji 1': {en: 'conquer', es: 'conquistar'},
  '√ji 2': {en: 'conquer', es: 'conquistar'},
  '√ju': {en: 'be fast', es: 'ser rápido'},
  '√jus': {en: 'like, please', es: 'gustar, agradar'},
  '√jut': {en: 'shine', es: 'brillar'},
  '√jāgar 1': {en: 'be awake, be watchful', es: 'estar despierto, estar atento'},
  '√jāgar 2': {en: 'be awake, be watchful', es: 'estar despierto, estar atento'},
  '√jī': {en: 'age, decay', es: 'envejecer, decaer'},
  '√jīr': {en: 'grow old, decay', es: 'envejecer, decaer'},
  '√jīv': {en: 'live', es: 'vivir'},
  '√kac': {en: 'shine, bind', es: 'brillar, atar'},
  '√kal 1': {en: 'spend time', es: 'pasar el tiempo'},
  '√kal 2': {en: 'accomplish', es: 'realizar'},
  '√kal 3': {en: 'calculate, add', es: 'calcular, sumar'},
  '√kalah': {en: 'argue', es: 'discutir'},
  '√kam 1': {en: 'go', es: 'ir'},
  '√kam 2': {en: 'desire', es: 'desear'},
  '√kamp': {en: 'shake, tremble', es: 'sacudir, temblar'},
  '√kan': {en: 'shine, like', es: 'brillar, gustar'},
  '√kand': {en: 'wail, cry out', es: 'lamentarse, gritar'},
  '√kap': {en: 'take pity', es: 'compadecerse'},
  '√kapp 1': {en: 'be fit, be suitable', es: 'ser apto, ser adecuado'},
  '√kapp 2': {en: 'think', es: 'pensar'},
  '√kar': {en: 'do, make', es: 'hacer'},
  '√kas 1': {en: 'drag, draw', es: 'arrastrar, tirar'},
  '√kas 2': {en: 'hurt, trouble', es: 'herir, molestar'},
  '√kass': {en: 'drag, draw along', es: 'arrastrar, tirar'},
  '√kat': {en: 'cut', es: 'cortar'},
  '√kath': {en: 'speak, narrate', es: 'hablar, narrar'},
  '√katth': {en: 'boast', es: 'jactarse'},
  '√kañc 1': {en: 'bind, cover', es: 'atar, cubrir'},
  '√kañc 2': {en: 'shine', es: 'brillar'},
  '√kaḍḍh': {en: 'drag, plough', es: 'arrastrar, arar'},
  '√kaṅkh 1': {en: 'wish for', es: 'desear'},
  '√kaṅkh 2': {en: 'doubt', es: 'dudar'},
  '√kaṇ': {en: 'make sound', es: 'hacer sonido'},
  '√kaṇḍ': {en: 'break, pierce', es: 'romper, perforar'},
  '√kaṭh 1': {en: 'live in distress', es: 'vivir en angustia'},
  '√kaṭh 2': {en: 'boil, burn', es: 'hervir, quemar'},
  '√kel': {en: 'care, cherish', es: 'cuidar, apreciar'},
  '√khac': {en: 'adorn, inlay', es: 'adornar, incrustar'},
  '√khal 1': {en: 'stumble, make mistake', es: 'tropezar, equivocarse'},
  '√khal 2': {en: 'clean, rinse', es: 'limpiar, enjuagar'},
  '√khal 3': {en: 'accumulate', es: 'acumular'},
  '√kham': {en: 'tolerate, endure', es: 'tolerar, soportar'},
  '√khambh': {en: 'prop, be stiff', es: 'apuntalar, estar rígido'},
  '√khan': {en: 'hurt, break', es: 'herir, romper'},
  '√khand': {en: 'jump', es: 'saltar'},
  '√khandh': {en: 'collect, accumulate', es: 'recolectar, acumular'},
  '√khar': {en: 'perish, break apart', es: 'perecer, desmoronarse'},
  '√khañj': {en: 'limp', es: 'cojear'},
  '√khaṇ': {en: 'dig', es: 'cavar'},
  '√khaṇḍ': {en: 'break', es: 'romper'},
  '√khi': {en: 'live, abide peacefully', es: 'vivir, morar en paz'},
  '√khip 1': {en: 'throw', es: 'lanzar'},
  '√khip 2': {en: 'sneeze', es: 'estornudar'},
  '√khiṭ': {en: 'frighten, scare', es: 'asustar, espantar'},
  '√khubh': {en: 'shake, agitate', es: 'sacudir, agitar'},
  '√khud': {en: 'be hungry', es: 'tener hambre'},
  '√khur': {en: 'cut', es: 'cortar'},
  '√khuṃs': {en: 'insult', es: 'insultar'},
  '√khyā': {en: 'announce', es: 'anunciar'},
  '√khā': {en: 'tell, announce', es: 'decir, anunciar'},
  '√khād': {en: 'chew', es: 'masticar'},
  '√khī': {en: 'exhaust, destroy', es: 'agotar, destruir'},
  '√kilam': {en: 'be weary', es: 'estar fatigado'},
  '√kilid': {en: 'be wet', es: 'estar mojado'},
  '√kilis 1': {en: 'be dirty, be molested', es: 'estar sucio, ser perturbado'},
  '√kilis 2': {en: 'trouble', es: 'perturbar'},
  '√kir': {en: 'scatter, sprinkle', es: 'esparcir, rociar'},
  '√kis': {en: 'be thin', es: 'ser delgado'},
  '√kit 1': {en: 'heal, cure', es: 'sanar, curar'},
  '√kit 2': {en: 'live', es: 'vivir'},
  '√kit 3': {en: 'know, doubt', es: 'conocer, dudar'},
  '√kitt': {en: 'make known', es: 'dar a conocer'},
  '√kiñc': {en: 'crush', es: 'aplastar'},
  '√ku': {en: 'sing, sound', es: 'cantar, sonar'},
  '√kuc': {en: 'contract', es: 'contraer'},
  '√kucch': {en: 'revile', es: 'injuriar'},
  '√kudh': {en: 'be angry', es: 'estar enojado'},
  '√kuh': {en: 'deceive', es: 'engañar'},
  '√kujj': {en: 'turn', es: 'girar'},
  '√kul': {en: 'be close', es: 'estar cerca'},
  '√kumār': {en: 'play', es: 'jugar'},
  '√kunth': {en: 'hurt, cause pain', es: 'herir, causar dolor'},
  '√kup': {en: 'shake, be angry', es: 'sacudir, estar enojado'},
  '√kur': {en: 'sound', es: 'sonar'},
  '√kus 1': {en: 'call, insult', es: 'llamar, insultar'},
  '√kus 2': {en: 'fill, enfold', es: 'llenar, envolver'},
  '√kus 3': {en: 'cut, tear', es: 'cortar, rasgar'},
  '√kuth': {en: 'boil, burn', es: 'hervir, quemar'},
  '√kuñc': {en: 'be crooked, be bent', es: 'ser torcido, estar doblado'},
  '√kuṇ': {en: 'be crooked, be bent', es: 'ser torcido, estar doblado'},
  '√kuṇḍ': {en: 'bend, mutilate', es: 'doblar, mutilar'},
  '√kuṇṭh': {en: 'be blunt, be lame', es: 'ser obtuso, ser cojo'},
  '√kuṭ 1': {en: 'be crooked, be bent', es: 'ser torcido, estar doblado'},
  '√kuṭ 2': {en: 'knock, beat', es: 'golpear, batir'},
  '√kuṭ 3': {en: 'cut', es: 'cortar'},
  '√kuṭṭ': {en: 'smash, powder', es: 'triturar, pulverizar'},
  '√kā': {en: 'makes sound', es: 'hacer sonido'},
  '√kās 1': {en: 'shine, be visible', es: 'brillar, ser visible'},
  '√kās 2': {en: 'cough', es: 'toser'},
  '√kī': {en: 'buy', es: 'comprar'},
  '√kīḷ': {en: 'play', es: 'jugar'},
  '√kūj': {en: 'make sound', es: 'hacer sonido'},
  '√kūl': {en: 'obstruct, embank', es: 'obstruir, represar'},
  '√kūḷ': {en: 'burn', es: 'quemar'},
  '√labh': {en: 'get', es: 'obtener'},
  '√lag': {en: 'stick, adhere', es: 'pegarse, adherirse'},
  '√lagg': {en: 'stick, adhere', es: 'pegarse, adherirse'},
  '√lagh': {en: 'lift up, jump', es: 'levantar, saltar'},
  '√lajj': {en: 'be ashamed', es: 'avergonzarse'},
  '√lakkh': {en: 'mark', es: 'marcar'},
  '√lamb': {en: 'hang', es: 'colgar'},
  '√lap': {en: 'speak, chat', es: 'hablar, charlar'},
  '√las': {en: 'shine, be active', es: 'brillar, ser activo'},
  '√lañch': {en: 'mark', es: 'marcar'},
  '√laḷ': {en: 'play, move about', es: 'jugar, moverse'},
  '√lih': {en: 'lick, lap', es: 'lamer'},
  '√likh': {en: 'scratch, write', es: 'rasgar, escribir'},
  '√lip': {en: 'coat, smear', es: 'recubrir, untar'},
  '√lis': {en: 'be small', es: 'ser pequeño'},
  '√liṅg 1': {en: 'embrace', es: 'abrazar'},
  '√liṅg 2': {en: 'differentiate sexually', es: 'diferenciar sexualmente'},
  '√loc': {en: 'see, illuminate', es: 'ver, iluminar'},
  '√lok': {en: 'look', es: 'mirar'},
  '√lu': {en: 'cut, reap, mow', es: 'cortar, cosechar, segar'},
  '√lubh 1': {en: 'be greedy', es: 'ser codicioso'},
  '√lubh 2': {en: 'fool, bewilder', es: 'engañar, confundir'},
  '√luj': {en: 'be broken apart', es: 'desmoronarse'},
  '√lup': {en: 'cut off, rob', es: 'cortar, robar'},
  '√luñc': {en: 'pluck out, tear', es: 'arrancar, rasgar'},
  '√luḷ': {en: 'agitate, be greedy', es: 'agitar, ser codicioso'},
  '√lā': {en: 'take', es: 'tomar'},
  '√lī 1': {en: 'stick, hide', es: 'pegarse, esconderse'},
  '√lī 2': {en: 'stick, hide', es: 'pegarse, esconderse'},
  '√mad': {en: 'be mad, be intoxicated', es: 'estar loco, estar embriagado'},
  '√madd': {en: 'crush, grind', es: 'aplastar, moler'},
  '√magg': {en: 'seek, search', es: 'buscar, indagar'},
  '√mah 1': {en: 'increase', es: 'aumentar'},
  '√mah 2': {en: 'venerate', es: 'venerar'},
  '√majj': {en: 'rub, polish', es: 'frotar, pulir'},
  '√makkh': {en: 'rub, erase', es: 'frotar, borrar'},
  '√mal': {en: 'dirty, stain', es: 'ensuciar, manchar'},
  '√man': {en: 'think', es: 'pensar'},
  '√mant': {en: 'counsel, invite', es: 'aconsejar, invitar'},
  '√manth': {en: 'churn, crush', es: 'batir, triturar'},
  '√mar': {en: 'die', es: 'morir'},
  '√maris': {en: 'be patient', es: 'ser paciente'},
  '√mas 1': {en: 'touch, rub', es: 'tocar, frotar'},
  '√mas 2': {en: 'buzz, hum', es: 'zumbar, tararear'},
  '√mas 3': {en: 'harm, destroy', es: 'dañar, destruir'},
  '√math': {en: 'churn, stir', es: 'batir, agitar'},
  '√mañc': {en: 'hold up, support', es: 'sostener, apoyar'},
  '√maṅg': {en: 'be auspicious', es: 'ser auspicioso'},
  '√maṇ': {en: 'abandon', es: 'abandonar'},
  '√maṇḍ': {en: 'adorn', es: 'adornar'},
  '√medh 1': {en: 'be wise', es: 'ser sabio'},
  '√medh 2': {en: 'hurt, harm', es: 'herir, dañar'},
  '√mhi': {en: 'smile', es: 'sonreír'},
  '√mi': {en: 'exchange, barter', es: 'intercambiar, trocar'},
  '√mid': {en: 'be fat', es: 'ser gordo'},
  '√migh': {en: 'sprinkle, shower', es: 'rociar, llover'},
  '√mih 1': {en: 'urinate, excrete', es: 'orinar, excretar'},
  '√mih 2': {en: 'smile, chuckle', es: 'sonreír, reírse'},
  '√milā': {en: 'shrink, wither', es: 'encogerse, marchitarse'},
  '√mis': {en: 'wink, blink', es: 'guiñar, parpadear'},
  '√miss': {en: 'mix, mingle', es: 'mezclar, mezclarse'},
  '√mith': {en: 'pair', es: 'emparejar'},
  '√mitt': {en: 'be friendly', es: 'ser amistoso'},
  '√mokkh': {en: 'be freed', es: 'ser liberado'},
  '√muc': {en: 'release, free', es: 'liberar, soltar'},
  '√mucch': {en: 'thicken, fixate', es: 'espesar, fijar'},
  '√mud': {en: 'be soft, be happy', es: 'ser suave, ser feliz'},
  '√muh': {en: 'be deluded, be confused', es: 'estar ofuscado, estar confundido'},
  '√mujj': {en: 'dive, sink, submerge', es: 'sumergirse, hundirse, sumergir'},
  '√mun': {en: 'think, know', es: 'pensar, conocer'},
  '√mus 1': {en: 'lie, forget', es: 'mentir, olvidar'},
  '√mus 2': {en: 'steal', es: 'robar'},
  '√muṇḍ': {en: 'be bald, shave', es: 'ser calvo, afeitar'},
  '√mā': {en: 'measure', es: 'medir'},
  '√mīl': {en: 'close eyes', es: 'cerrar los ojos'},
  '√mūl': {en: 'support', es: 'apoyar'},
  '√nabh': {en: 'burst, split', es: 'reventar, partir'},
  '√nad': {en: 'roar', es: 'rugir'},
  '√nadh': {en: 'wrap, twist', es: 'envolver, torcer'},
  '√nah': {en: 'bind, arm', es: 'atar, armar'},
  '√nakkh': {en: 'attain, arrive', es: 'alcanzar, llegar'},
  '√nam': {en: 'bend', es: 'doblar'},
  '√namass': {en: 'bow, worship', es: 'inclinarse, adorar'},
  '√nand': {en: 'delight, enjoy', es: 'deleitar, disfrutar'},
  '√nar': {en: 'lead', es: 'guiar'},
  '√nas': {en: 'be lost, disappear', es: 'perderse, desaparecer'},
  '√nat': {en: 'dance, act', es: 'danzar, actuar'},
  '√naṭ': {en: 'bend, dance', es: 'doblar, danzar'},
  '√ness': {en: 'take away', es: 'llevar'},
  '√nhā': {en: 'bathe', es: 'bañarse'},
  '√nind': {en: 'blame, abuse', es: 'culpar, insultar'},
  '√nud': {en: 'drive out, reject', es: 'expulsar, rechazar'},
  '√nādh': {en: 'beg', es: 'mendigar'},
  '√nāth': {en: 'have power, protect', es: 'tener poder, proteger'},
  '√nī': {en: 'lead, carry', es: 'guiar, llevar'},
  '√nīl': {en: 'be blue', es: 'ser azul'},
  '√op': {en: 'placing', es: 'colocar'},
  '√pabb': {en: 'grow', es: 'crecer'},
  '√pac': {en: 'cook, mature, ripen', es: 'cocinar, madurar'},
  '√pad': {en: 'go, step', es: 'ir, pisar'},
  '√palus': {en: 'burn', es: 'arder'},
  '√palā': {en: 'run away, flee', es: 'huir, escapar'},
  '√panth': {en: 'go, move', es: 'ir, moverse'},
  '√par': {en: 'be active', es: 'ser activo'},
  '√pas': {en: 'tie, bind', es: 'atar, amarrar'},
  '√pat 1': {en: 'fall', es: 'caer'},
  '√pat 2': {en: 'command, control', es: 'comandar, controlar'},
  '√path 1': {en: 'go, move', es: 'ir, moverse'},
  '√path 2': {en: 'expand', es: 'expandir'},
  '√pañc': {en: 'expand, spread', es: 'expandir, extender'},
  '√pañh': {en: 'ask, question', es: 'preguntar, cuestionar'},
  '√paṇ': {en: 'trade, barter', es: 'comerciar, trocar'},
  '√paṇḍ': {en: 'mock, tease', es: 'burlarse, provocar'},
  '√paṭ 1': {en: 'split, tear', es: 'partir, rasgar'},
  '√paṭ 2': {en: 'go', es: 'ir'},
  '√paṭh': {en: 'read, recite', es: 'leer, recitar'},
  '√pel': {en: 'move, propel', es: 'mover, impulsar'},
  '√phal 1': {en: 'split open', es: 'abrir, partir'},
  '√phal 2': {en: 'fruit, ripen', es: 'fructificar, madurar'},
  '√phand': {en: 'shake, quiver', es: 'temblar, estremecerse'},
  '√phar': {en: 'suffuse, pervade', es: 'impregnar, permear'},
  '√phaṇ': {en: 'skim', es: 'deslizarse'},
  '√phull': {en: 'expand, bloom', es: 'expandir, florecer'},
  '√phus 1': {en: 'touch', es: 'tocar'},
  '√phus 2': {en: 'sprinkle, splash', es: 'rociar, salpicar'},
  '√phuṇ': {en: 'suffers', es: 'sufrir'},
  '√phuṭ 1': {en: 'beat, smash', es: 'golpear, aplastar'},
  '√phuṭ 2': {en: 'swell, burst', es: 'hincharse, reventar'},
  '√phā': {en: 'swell, get fat', es: 'hincharse, engordar'},
  '√pih': {en: 'desire, envy', es: 'desear, envidiar'},
  '√pis 1': {en: 'send', es: 'enviar'},
  '√pis 2': {en: 'grind, hurt', es: 'moler, herir'},
  '√pis 3': {en: 'speak ill', es: 'difamar'},
  '√piṇḍ': {en: 'collect', es: 'recolectar'},
  '√piṭ': {en: 'collect', es: 'recolectar'},
  '√plu 1': {en: 'float, swim', es: 'flotar, nadar'},
  '√plu 2': {en: 'spring, swing', es: 'saltar, balancearse'},
  '√pu': {en: 'purify, cleanse', es: 'purificar, limpiar'},
  '√pucch': {en: 'ask, question', es: 'preguntar, cuestionar'},
  '√pul': {en: 'increase', es: 'aumentar'},
  '√pupph': {en: 'flower, expand', es: 'florecer, expandir'},
  '√pus': {en: 'nourish, take care', es: 'nutrir, cuidar'},
  '√puth': {en: 'expand', es: 'expandir'},
  '√puñch': {en: 'wipe', es: 'limpiar'},
  '√puṇ': {en: 'be skilful, be precise', es: 'ser hábil, ser preciso'},
  '√puṭ': {en: 'wrap, envelop', es: 'envolver'},
  '√puṭh': {en: 'beat, hurt', es: 'golpear, herir'},
  '√pā 1': {en: 'drink', es: 'beber'},
  '√pā 2': {en: 'protect, guard', es: 'proteger, custodiar'},
  '√pāl': {en: 'protect', es: 'proteger'},
  '√pāy': {en: 'increase', es: 'aumentar'},
  '√pī': {en: 'love, please', es: 'amar, complacer'},
  '√pīḷ': {en: 'press, crush', es: 'presionar, aplastar'},
  '√pīṇ': {en: 'please, swell', es: 'complacer, hincharse'},
  '√pūj': {en: 'honour, venerate', es: 'honrar, venerar'},
  '√pūr': {en: 'fill, fulfil', es: 'llenar, cumplir'},
  '√pūy': {en: 'rot, fester', es: 'pudrirse, supurar'},
  '√rabh 1': {en: 'begin', es: 'comenzar'},
  '√rabh 2': {en: 'be aroused, be violent', es: 'excitarse, ser violento'},
  '√rac': {en: 'prepare, arrange', es: 'preparar, ordenar'},
  '√rah': {en: 'leave, desert', es: 'dejar, abandonar'},
  '√raj 1': {en: 'desire', es: 'desear'},
  '√raj 2': {en: 'colour', es: 'colorear'},
  '√rakkh': {en: 'protect', es: 'proteger'},
  '√ram 1': {en: 'delight, please', es: 'deleitar, complacer'},
  '√ram 2': {en: 'stop, abstain', es: 'detenerse, abstenerse'},
  '√randh 1': {en: 'cook', es: 'cocinar'},
  '√randh 2': {en: 'hurt, wound', es: 'herir, lastimar'},
  '√ras': {en: 'taste', es: 'saborear'},
  '√rañj': {en: 'dye, desire', es: 'teñir, desear'},
  '√raṇ': {en: 'conflict, make war', es: 'luchar, guerrear'},
  '√ric': {en: 'empty', es: 'vaciar'},
  '√ris': {en: 'hurt', es: 'herir'},
  '√ru': {en: 'cry, howl', es: 'llorar, aullar'},
  '√ruc': {en: 'shine, like', es: 'brillar, gustar'},
  '√rud': {en: 'cry', es: 'llorar'},
  '√rudh 1': {en: 'obstruct', es: 'obstruir'},
  '√rudh 2': {en: 'please, accept', es: 'complacer, aceptar'},
  '√ruh': {en: 'ascend, grow', es: 'ascender, crecer'},
  '√ruj': {en: 'hurt, be painful', es: 'herir, ser doloroso'},
  '√rup': {en: 'be broken apart, hurt', es: 'romperse, herir'},
  '√rus': {en: 'be angry', es: 'estar enojado'},
  '√rādh': {en: 'succeed, please', es: 'tener éxito, complacer'},
  '√rāj': {en: 'rule, shine', es: 'gobernar, brillar'},
  '√rūp': {en: 'form, produce', es: 'formar, producir'},
  '√sad': {en: 'sink, sit, settle', es: 'hundirse, sentarse, asentarse'},
  '√sadd': {en: 'sound', es: 'sonar'},
  '√sadh': {en: 'mock, ridicule', es: 'burlarse, ridiculizar'},
  '√sah 1': {en: 'overcome, prevail', es: 'superar, prevalecer'},
  '√sah 2': {en: 'be able', es: 'ser capaz'},
  '√saj 1': {en: 'stick, cling', es: 'pegarse, aferrarse'},
  '√saj 2': {en: 'relinquish, let loose', es: 'soltar, liberar'},
  '√saj 3': {en: 'embrace', es: 'abrazar'},
  '√sajj 1': {en: 'relinquish, let loose', es: 'soltar, liberar'},
  '√sajj 2': {en: 'prepare, decorate', es: 'preparar, decorar'},
  '√sak': {en: 'be able, be powerful', es: 'ser capaz, ser poderoso'},
  '√sakk': {en: 'move', es: 'moverse'},
  '√sam 1': {en: 'be calm, be tired', es: 'estar calmado, estar cansado'},
  '√sam 2': {en: 'exert, strive', es: 'esforzarse, luchar'},
  '√sambh 1': {en: 'be calm, be confident', es: 'estar calmado, tener confianza'},
  '√sambh 2': {en: 'reach, attain', es: 'alcanzar, lograr'},
  '√san': {en: 'like, love', es: 'gustar, amar'},
  '√sand': {en: 'flow', es: 'fluir'},
  '√sap': {en: 'curse', es: 'maldecir'},
  '√sapp': {en: 'crawl', es: 'arrastrarse'},
  '√sar 1': {en: 'go, flow', es: 'ir, fluir'},
  '√sar 2': {en: 'remember', es: 'recordar'},
  '√sar 3': {en: 'make sound', es: 'producir sonido'},
  '√sar 4': {en: 'shine', es: 'brillar'},
  '√sar 5': {en: 'hurt, injure', es: 'herir, lesionar'},
  '√sas 1': {en: 'breath', es: 'respirar'},
  '√sas 2': {en: 'slaughter', es: 'masacrar'},
  '√sañj': {en: 'clasp, embrace', es: 'agarrar, abrazar'},
  '√saṃs 1': {en: 'proclaim, praise', es: 'proclamar, alabar'},
  '√saṃs 2': {en: 'wish, desire', es: 'desear, anhelar'},
  '√saṅk': {en: 'doubt, suspect', es: 'dudar, sospechar'},
  '√saṇ': {en: 'make sound', es: 'producir sonido'},
  '√saṭ': {en: 'split', es: 'partir'},
  '√saṭh': {en: 'deceive', es: 'engañar'},
  '√sev': {en: 'serve, associate', es: 'servir, asociarse'},
  '√si 1': {en: 'depend on, associate with', es: 'depender de, asociarse con'},
  '√si 2': {en: 'bind', es: 'atar'},
  '√si 3': {en: 'sharpen', es: 'afilar'},
  '√si 4': {en: 'smile', es: 'sonreír'},
  '√sic': {en: 'sprinkle, pour', es: 'rociar, verter'},
  '√sid 1': {en: 'sweat, steam', es: 'sudar, evaporarse'},
  '√sid 2': {en: 'be cool', es: 'ser fresco'},
  '√sidh 1': {en: 'prevent, prohibit', es: 'prevenir, prohibir'},
  '√sidh 2': {en: 'succeed, be accomplished', es: 'tener éxito, lograr'},
  '√sikkh': {en: 'learn, train', es: 'aprender, entrenar'},
  '√silis': {en: 'embrace, cling', es: 'abrazar, aferrarse'},
  '√silok': {en: 'be famous', es: 'ser famoso'},
  '√silāgh': {en: 'boast', es: 'jactarse'},
  '√sinā': {en: 'bathe', es: 'bañarse'},
  '√sis': {en: 'remain, distinguish', es: 'permanecer, distinguir'},
  '√sit': {en: 'be white', es: 'ser blanco'},
  '√siv 1': {en: 'sew', es: 'coser'},
  '√siv 2': {en: 'warm', es: 'calentar'},
  '√siḷ': {en: 'whistle', es: 'silbar'},
  '√siṃs': {en: 'hope, wish', es: 'esperar, desear'},
  '√siṅgh': {en: 'sniff, smell', es: 'olfatear, oler'},
  '√snih': {en: 'love, be moist', es: 'amar, estar húmedo'},
  '√su 1': {en: 'hear', es: 'oír'},
  '√su 2': {en: 'flow', es: 'fluir'},
  '√su 3': {en: 'extract, distil', es: 'extraer, destilar'},
  '√su 4': {en: 'generate, beget', es: 'generar, engendrar'},
  '√subh': {en: 'shine, adorn', es: 'brillar, adornar'},
  '√suc 1': {en: 'grieve', es: 'lamentar'},
  '√suc 2': {en: 'be pure, be bright', es: 'ser puro, ser brillante'},
  '√sudh': {en: 'be pure', es: 'ser puro'},
  '√sukh': {en: 'please, be comfortable', es: 'complacer, estar cómodo'},
  '√sumbh': {en: 'throw, strike', es: 'lanzar, golpear'},
  '√sup': {en: 'lie down, sleep', es: 'acostarse, dormir'},
  '√sur': {en: 'shine, be supreme', es: 'brillar, ser supremo'},
  '√sus': {en: 'dry, wither', es: 'secar, marchitarse'},
  '√sā': {en: 'complete, accomplish', es: 'completar, lograr'},
  '√sād': {en: 'taste, relish', es: 'saborear, degustar'},
  '√sādh': {en: 'accomplish', es: 'lograr'},
  '√sās': {en: 'order, instruct', es: 'ordenar, instruir'},
  '√sāy': {en: 'taste', es: 'saborear'},
  '√sī': {en: 'lie, sleep', es: 'yacer, dormir'},
  '√sīl': {en: 'conduct oneself', es: 'conducirse'},
  '√sūc': {en: 'indicate', es: 'indicar'},
  '√sūd': {en: 'set in order', es: 'ordenar'},
  '√tacch': {en: 'cut, chop', es: 'cortar, talar'},
  '√tajj': {en: 'frighten, threaten', es: 'asustar, amenazar'},
  '√takk': {en: 'think', es: 'pensar'},
  '√tal': {en: 'support, rest on', es: 'apoyar, descansar sobre'},
  '√tam': {en: 'faint', es: 'desmayarse'},
  '√tan': {en: 'stretch, extend', es: 'estirar, extender'},
  '√tand': {en: 'be slow, be lazy', es: 'ser lento, ser perezoso'},
  '√tap': {en: 'burn, radiate heat', es: 'arder, irradiar calor'},
  '√tapp 1': {en: 'regret', es: 'lamentar'},
  '√tapp 2': {en: 'satisfy', es: 'satisfacer'},
  '√tar 1': {en: 'cross', es: 'cruzar'},
  '√tar 2': {en: 'hurry', es: 'apresurarse'},
  '√tas 1': {en: 'tremble, fear', es: 'temblar, temer'},
  '√tas 2': {en: 'thirst', es: 'tener sed'},
  '√tas 3': {en: 'decorate, impale', es: 'decorar, empalar'},
  '√taḷ': {en: 'beat', es: 'golpear'},
  '√thak': {en: 'close', es: 'cerrar'},
  '√thal': {en: 'be firm', es: 'ser firme'},
  '√tham': {en: 'hang', es: 'colgar'},
  '√thambh': {en: 'support, be stiff', es: 'apoyar, ser rígido'},
  '√than': {en: 'roar, thunder', es: 'rugir, tronar'},
  '√thar': {en: 'spread, expand', es: 'extender, expandir'},
  '√then': {en: 'steal', es: 'robar'},
  '√thom': {en: 'praise', es: 'alabar'},
  '√thu 1': {en: 'moan, groan', es: 'gemir, quejarse'},
  '√thu 2': {en: 'be familiar, praise', es: 'ser familiar, alabar'},
  '√thu 3': {en: 'praise', es: 'alabar'},
  '√thī': {en: 'stiffen, be compact', es: 'endurecer, ser compacto'},
  '√thūl': {en: 'be fat, be coarse', es: 'ser gordo, ser tosco'},
  '√tij 1': {en: 'be sharp, be hot', es: 'ser afilado, ser caliente'},
  '√tij 2': {en: 'be sharp, be bitter', es: 'ser afilado, ser amargo'},
  '√tij 3': {en: 'endure', es: 'soportar'},
  '√tim': {en: 'be wet', es: 'estar mojado'},
  '√tir': {en: 'cross', es: 'cruzar'},
  '√tis': {en: 'satisfy', es: 'satisfacer'},
  '√tras': {en: 'fear, shake', es: 'temer, temblar'},
  '√tud': {en: 'prick, stab', es: 'pinchar, apuñalar'},
  '√tul': {en: 'weigh', es: 'pesar'},
  '√tur 1': {en: 'hurt, be sick', es: 'herir, estar enfermo'},
  '√tur 2': {en: 'hurry, be quick', es: 'apresurarse, ser rápido'},
  '√tus': {en: 'be content, be pleased', es: 'estar contento, estar complacido'},
  '√tuvaṭṭ': {en: 'lie down', es: 'acostarse'},
  '√tuḍ': {en: 'prick, stab', es: 'pinchar, apuñalar'},
  '√tā': {en: 'protect, preserve', es: 'proteger, preservar'},
  '√tīr': {en: 'investigate, complete', es: 'investigar, completar'},
  '√tūl': {en: 'be light', es: 'ser liviano'},
  '√uc': {en: 'comfort', es: 'consolar'},
  '√ud': {en: 'be wet', es: 'estar mojado'},
  '√udrabh': {en: 'eat', es: 'comer'},
  '√uj': {en: 'be straight', es: 'ser recto'},
  '√ujjh': {en: 'leave, discard', es: 'dejar, descartar'},
  '√ukkh': {en: 'sprinkle, pour', es: 'rociar, verter'},
  '√us': {en: 'be hot', es: 'ser caliente'},
  '√usūy': {en: 'be irritated, be jealous', es: 'estar irritado, estar celoso'},
  '√uñch': {en: 'glean', es: 'espigar'},
  '√vac': {en: 'say, speak', es: 'decir, hablar'},
  '√vad 1': {en: 'say, speak', es: 'decir, hablar'},
  '√vad 2': {en: 'salute, praise', es: 'saludar, alabar'},
  '√vaddh': {en: 'grow, increase', es: 'crecer, aumentar'},
  '√vadh': {en: 'hurt, slaughter', es: 'herir, masacrar'},
  '√vagg': {en: 'dance, jump', es: 'danzar, saltar'},
  '√vah': {en: 'carry, bring', es: 'llevar, traer'},
  '√vaj': {en: 'go on', es: 'proseguir'},
  '√vajj': {en: 'turn, avoid', es: 'girar, evitar'},
  '√val': {en: 'turn', es: 'girar'},
  '√vall': {en: 'turn', es: 'girar'},
  '√vam': {en: 'eject, vomit', es: 'expulsar, vomitar'},
  '√vambh': {en: 'despise', es: 'despreciar'},
  '√van': {en: 'like, desire', es: 'gustar, desear'},
  '√vand': {en: 'bow, honour', es: 'inclinarse, honrar'},
  '√vap': {en: 'sow, shave', es: 'sembrar, afeitar'},
  '√var 1': {en: 'cover, dress, restrain', es: 'cubrir, vestir, contener'},
  '√var 2': {en: 'wish, choose', es: 'desear, elegir'},
  '√vas 1': {en: 'live', es: 'vivir'},
  '√vas 2': {en: 'wear, dress', es: 'vestir'},
  '√vas 3': {en: 'want, control', es: 'querer, controlar'},
  '√vass 1': {en: 'rain', es: 'llover'},
  '√vass 2': {en: 'howl, roar, bark', es: 'aullar, rugir, ladrar'},
  '√vat': {en: 'be, proceed', es: 'ser, proceder'},
  '√vatt': {en: 'be, proceed', es: 'ser, proceder'},
  '√vañc 1': {en: 'be bent, deceive', es: 'estar torcido, engañar'},
  '√vañc 2': {en: 'go around', es: 'rodear'},
  '√vaḍḍh': {en: 'grow, increase', es: 'crecer, aumentar'},
  '√vaḷañj': {en: 'use', es: 'usar'},
  '√vaṇ': {en: 'injure, wound', es: 'lesionar, herir'},
  '√vaṇṇ': {en: 'praise', es: 'alabar'},
  '√vaṭ': {en: 'divide', es: 'dividir'},
  '√vaṭṭ': {en: 'turn', es: 'girar'},
  '√ve': {en: 'weave', es: 'tejer'},
  '√vedh': {en: 'shake, fear', es: 'temblar, temer'},
  '√vell': {en: 'shake, sway', es: 'sacudir, balancearse'},
  '√veṭh': {en: 'wind, twist', es: 'enrollar, torcer'},
  '√vhe': {en: 'call, name', es: 'llamar, nombrar'},
  '√vi': {en: 'weave', es: 'tejer'},
  '√vic': {en: 'separate', es: 'separar'},
  '√vid 1': {en: 'know, sense, feel', es: 'conocer, percibir, sentir'},
  '√vid 2': {en: 'know', es: 'conocer'},
  '√vid 3': {en: 'feel, like', es: 'sentir, gustar'},
  '√vid 4': {en: 'get, find', es: 'obtener, encontrar'},
  '√vid 5': {en: 'know, understand', es: 'conocer, comprender'},
  '√vid 6': {en: 'be found, exist', es: 'encontrarse, existir'},
  '√vidh': {en: 'throw, pierce', es: 'lanzar, perforar'},
  '√vij': {en: 'shake, be afraid, be in awe', es: 'temblar, temer, estar asombrado'},
  '√vis 1': {en: 'enter', es: 'entrar'},
  '√vis 2': {en: 'be active, serve', es: 'ser activo, servir'},
  '√vu': {en: 'weave, cover', es: 'tejer, cubrir'},
  '√vyadh': {en: 'strike, pierce', es: 'golpear, perforar'},
  '√vyath': {en: 'fear, shake', es: 'temer, temblar'},
  '√vā': {en: 'blow, emit odour', es: 'soplar, emitir olor'},
  '√vās': {en: 'perfume', es: 'perfumar'},
  '√vī': {en: 'go', es: 'ir'},
  '√vīj': {en: 'fan', es: 'abanicar'},
  '√vīr': {en: 'be heroic, be hostile', es: 'ser heroico, ser hostil'},
  '√yaj': {en: 'honour, sacrifice', es: 'honrar, sacrificar'},
  '√yakkh': {en: 'worship', es: 'adorar'},
  '√yam 1': {en: 'control, strive, end', es: 'controlar, esforzarse, terminar'},
  '√yam 2': {en: 'support, stretch', es: 'apoyar, estirar'},
  '√yant': {en: 'bind', es: 'atar'},
  '√yas': {en: 'strive, struggle', es: 'esforzarse, luchar'},
  '√yat 1': {en: 'arrange, hand over', es: 'ordenar, entregar'},
  '√yat 2': {en: 'stretch, strive', es: 'estirar, esforzarse'},
  '√yu': {en: 'unite, fasten', es: 'unir, sujetar'},
  '√yudh': {en: 'fight', es: 'luchar'},
  '√yuj': {en: 'yoke, join', es: 'uncir, unir'},
  '√yā': {en: 'go', es: 'ir'},
  '√yāc': {en: 'beg', es: 'mendigar'},
  '√yūh': {en: 'carry, bring', es: 'llevar, traer'},
  '√ñā': {en: 'know', es: 'conocer'},
  '√ādā': {en: 'take, seize', es: 'tomar, agarrar'},
  '√āgam': {en: 'wait', es: 'esperar'},
  '√āp': {en: 'be wet', es: 'estar mojado'},
  '√ās': {en: 'sit', es: 'sentarse'},
  '√īh': {en: 'strive', es: 'esforzarse'},
  '√īr 1': {en: 'move, shake', es: 'mover, sacudir'},
  '√īr 2': {en: 'speak', es: 'hablar'},
  '√īs': {en: 'have power', es: 'tener poder'},
  '√ḍah': {en: 'burn', es: 'quemar'},
  '√ḍaṃs': {en: 'bite, sting', es: 'morder, picar'},
  '√ḍi 1': {en: 'fly', es: 'volar'},
  '√ḍi 2': {en: 'trap', es: 'atrapar'},
  '√ṭaṅk': {en: 'seal, cover', es: 'sellar, cubrir'},
  '√ṭhubh': {en: 'spit', es: 'escupir'},
  '√ṭhā': {en: 'stand', es: 'estar de pie'}
};